site_name: fastEDM Python Package

nav:
  - Home: index.md
  # - Demo: manifolds.md

theme:
  name: material

  icon:
    logo: fontawesome/solid/wave-square

  # These are the default colours
  palette:
    primary: indigo
    accent: indigo
    
  font:
    text: Alegreya Sans
  
  hljs_languages:
    - python

markdown_extensions:
  - admonition
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - assets/setup-mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra:
  analytics:
    provider: google
    property: G-Y5Q06PR748