[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.10.0",
    "numpy>=1.17.0",
    "scipy>=1.9.2"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/tests/test.py"
test-skip = "*universal2:arm64"
